// Autogenerated main.js file

require("jsb_cocos2d.js");
require("jsb_cocosbuilder.js");
require("jsb_opengl.js");
require("jsb_sys.js");




require("header.js")



//function login()
//{
    
//}

function run()
{


    /*onLogin = function(userid,name){
        cc.log("login")
        cc.log(userid+name)
    }
    wl.dispatcher.register("login",c.t,c,1)

    wl.dispatcher.notify("login","userid","name")
    */
	//cc.FileUtils.getInstance().loadFilenameLookup("fileLookup.plist");
    //cc.Texture2D.setDefaultAlphaPixelFormat(6);
	var director = cc.Director.getInstance();
    var scene = wl.create_loginscene();//cc.BuilderReader.loadAsScene("loginscene");


    cc.log(cc.Util.macAddress())

    //var info = {"code":"login","userid":"1","ip":"192.168.0.1","pwd":"222","time":"1"}
    //wl.http.send(info)


    var runningScene = director.getRunningScene();
    if (runningScene === null) director.runWithScene(scene);
    else director.replaceScene(scene);

    /*    var imagepicker = cc.ImagePicker.getInstance()
    imagepicker.on_pick = function(pickdata){
    cc.log("width:"+pickdata.getWidth())
    cc.log("height:"+pickdata.getHeight())
    cc.log("data:"+pickdata.toBase64().length)
    cc.log("datazip:"+pickdata.toBase64())

    var img = new cc.Image()
    img.initWithBase64(pickdata.toBase64(),pickdata.getWidth(),pickdata.getHeight())

    var t2d = cc.Texture2D.create()
    t2d.initWithImage(img)
    //t2d.initWithImage(pickdata)
    var spr = cc.Sprite.createWithTexture(t2d)

    var runningScene = director.getRunningScene();
    scene.addChild(spr)
    spr.setPosition(cc.p(160,240))

    cc.log(t2d)
}*/
//imagepicker.useCamera(imagepicker,imagepicker.on_pick,256,256,true)
  
}

if(NOTUSE_CCB){
	run();
}
