// Autogenerated main.js file

require("jsb_cocos2d.js");
require("jsb_cocosbuilder.js");
require("jsb_opengl.js");
require("jsb_sys.js");




require("header.js")




function run()
{
  
    wl.run_scene("loginscene");

  
}

if(!USE_CCB){
	run();
}
