// Autogenerated main.js file

require("jsb_cocos2d.js");
require("jsb_cocosbuilder.js");
require("jsb_opengl.js");
require("jsb_sys.js");

require("hashlib.js")

SECRET_KEY = 'ebv2*u)qdlk+u9wdtl-1cl6ct5gfj-3wu$!6of*gjy+f2zsc@b'

function main()
{
	//cc.FileUtils.getInstance().loadFilenameLookup("fileLookup.plist");
    //cc.Texture2D.setDefaultAlphaPixelFormat(6);
	var director = cc.Director.getInstance();
    var scene = cc.Scene.create();//cc.BuilderReader.loadAsScene("MainScene");

    scene.lbl = cc.LabelTTF.create("connecting","",24)
    scene.lbl.setPosition(cc.p(160,240))
    scene.addChild(scene.lbl)

    scene.httpclient = cc.HttpClient.getInstance()
    var req = new cc.HttpRequest()
    req.setRequestType(1)
    var info = '{"id":"1","ip":"192.168.0.1","pwd":"123",time="1"}'
    var sig = hex_md5(info+SECRET_KEY)
    var data = 'info='+info+'&sig='+sig
    req.setUrl('http://www.loviyou.com:8080/anotherworld/account/')

    req.setRequestData(data,data.length)

    
    cc.log(data)
    scene.on_login = function(httpclient,response){
        cc.log("login response:")
        cc.log(response.getResponseData())
        
    }

    req.setResponseCallback(scene,scene.on_login)
    scene.httpclient.send(req)

    var runningScene = director.getRunningScene();
    if (runningScene === null) director.runWithScene(scene);
    else director.replaceScene(scene);
}
main();