// Autogenerated main.js file

require("jsb_cocos2d.js");
require("jsb_cocosbuilder.js");
require("jsb_opengl.js");
require("jsb_sys.js");


require("config.js")
require("msg.js")

require("extra/http.js")


function main()
{
   var datetime = new Date();
   cc.log(datetime)
	//cc.FileUtils.getInstance().loadFilenameLookup("fileLookup.plist");
    //cc.Texture2D.setDefaultAlphaPixelFormat(6);
	var director = cc.Director.getInstance();
    var scene = cc.Scene.create();//cc.BuilderReader.loadAsScene("MainScene");

    scene.lbl = cc.LabelTTF.create("connecting","",24)
    scene.lbl.setPosition(cc.p(160,240))
    scene.addChild(scene.lbl)

  

    var info = {"code":"login","userid":"1","ip":"192.168.0.1","pwd":"222","time":"1"}
    http.send(info)
   

    var runningScene = director.getRunningScene();
    if (runningScene === null) director.runWithScene(scene);
    else director.replaceScene(scene);
}
main();